---
name: AntiFallDamage
version: 2.0.2
main: NhanAZ\AntiFallDamage\Main
api: 5.0.0
src-namespace-prefix: NhanAZ\AntiFallDamage
author: NhanAZ
website: https://github.com/NhanAZ
description: Prevent fall damage

permissions:
  antifalldamage.use:
    description: Allows players to be unaffected by falling damage
    default: op
...
